libgit2-dev is needed to compile pygit2 dependency
    fatal error: git2.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1